### ISSUE TITLE
Joint order / URDF file used

### ISSUE THREAD

**Issue by JLBicho** [YanjieZe/Improved-3D-Diffusion-Policy#11]
Hello,

I'm preparing a visualization of your dataset using Foxglove and I'm currently blocked due to the joint order and missing a URDF file. 

In file [action_util.py](https://github.com/YanjieZe/Humanoid-Teleoperation/blob/de25d719a2e961d071d99b62560a71657848208f/humanoid_teleoperation/scripts/action_util.py#L13), there are two functions to change from 32 joints to 25 joints. There is a mention to a `hand` joints.

```
def joint32_to_joint25(joint):
    #  q_upper_body = [0.0, waist_pitch, 0.0, head_pitch, 0.0, head_yaw]
    # used joint: waist 1 + head 2 + arm 5*2 + hand 6*2 = 25
```

However, in file [config_GR1_T2-yaml](https://github.com/YanjieZe/Humanoid-Teleoperation/blob/de25d719a2e961d071d99b62560a71657848208f/humanoid_teleoperation/teleop-zenoh/config_GR1_T2.yaml), the list of joints does not include a `hand` joint. In addition, the order of the joints is different. 

```
names: [
      "l_hip_roll", "l_hip_yaw", "l_hip_pitch", "l_knee_pitch", "l_ankle_pitch", "l_ankle_roll",
      "r_hip_roll", "r_hip_yaw", "r_hip_pitch", "r_knee_pitch", "r_ankle_pitch", "r_ankle_roll",
      "joint_waist_yaw", "joint_waist_pitch", "joint_waist_roll",
      "joint_head_pitch", "joint_head_roll", "joint_head_yaw",
      "l_shoulder_pitch", "l_shoulder_roll", "l_shoulder_yaw", "l_elbow_pitch", "l_wrist_yaw", "l_wrist_roll", "l_wrist_pitch",
      "r_shoulder_pitch", "r_shoulder_roll", "r_shoulder_yaw", "r_elbow_pitch", "r_wrist_yaw", "r_wrist_roll", "r_wrist_pitch",
      ]
```

Given that there is no URDF or robot description file in the repo, I am using the one found in [Wiki-GRx-Models](https://github.com/FFTAI/Wiki-GRx-Models/tree/master). In particular, I'm using file [GR1T2_simple.urdf](https://github.com/FFTAI/Wiki-GRx-Models/blob/master/GR1_legacy/GR1/GR1T2/urdf/GR1T2_simple.urdf), because it is the one I found that has 32 joints, has your dataset uses.

Could you please tell me where the joints name and order from the dataset `action` to generate a URDF visualization.

Thank you

**Comment by YanjieZe** [comment]
Hi, thank you for your interest! Currently I do not have the urdf for this, but using the official urdf from Fourier should be ok.
For hands, we are using Inspire Hand, so maybe you can refer to their official urdf.

**Comment by JLBicho** [comment]
Hello again,

Thank you for answering and sorry to open a closed issue.

Is there a definition of the order of the 32/25 joints? I understand you are not using all joints from G1T2 and the Inspire Hand, so it would be helpful to understand which joints are used and the order in the joint32_to_joint25 function.

Thank you!
