### ISSUE TITLE
Some questions on  inference time 

### ISSUE THREAD

**Issue by zywbupt** [YanjieZe/Improved-3D-Diffusion-Policy#12]
The code in deploy  send obs_dict data which include 'agent_pos'  'point_cloud' 'image' into policy wtih  action = policy(obs_dict)[0] to get action. However, in the duffusion policy forword it needs self.normalizer = self.get_normalizer('limits', obs_dict) for  the data,  and there is no code for this dict normalize. I added     '
```
def get_normalizer(self, mode='limits', **kwargs):
        data = {'action': self.replay_buffer['action']}
        normalizer = LinearNormalizer()
        normalizer.fit(data=data, last_n_dims=1, mode=mode, **kwargs)

        normalizer['point_cloud'] = SingleFieldLinearNormalizer.create_identity()
        # normalizer['agent_pos'] = SingleFieldLinearNormalizer.create_identity()
        normalizer['qpos'] = SingleFieldLinearNormalizer.create_identity()
        
        return normalizer 
```
to normaize the input as the same as dataloader input
but get random output
so i what to know if it is need to normize when to deploy it, and how can i change the code to make deploy work well

**Comment by YanjieZe** [comment]
Hi, thank you for your interest. I think the normalizer is from the dataset class, and is set by [this function](https://github.com/YanjieZe/Improved-3D-Diffusion-Policy/blob/0595aa1c7f75b35e6fc45759e0bd92f01153a95f/Improved-3D-Diffusion-Policy/diffusion_policy_3d/policy/diffusion_pointcloud_policy.py#L312)

**Comment by zywbupt** [comment]
where can i add the setcode， in the idp3_workspace.py i the data is normalized first and then using self.model.set_normalizer(normalizer) to set the normalizer, but in the deploy stage, i can not find the set step in your code.

**Comment by zywbupt** [comment]
> Hi, thank you for your interest. I think the normalizer is from the dataset class, and is set by [this function](https://github.com/YanjieZe/Improved-3D-Diffusion-Policy/blob/0595aa1c7f75b35e6fc45759e0bd92f01153a95f/Improved-3D-Diffusion-Policy/diffusion_policy_3d/policy/diffusion_pointcloud_policy.py#L312)
Thanks for you reply. But where can i add the setcode， in the idp3_workspace.py i the data is normalized first and then using self.model.set_normalizer(normalizer) to set the normalizer, but in the deploy stage, i can not find the set step in your code.
