### ISSUE TITLE
Report a Problem

### ISSUE THREAD

**Issue by Ju6276** [YanjieZe/Improved-3D-Diffusion-Policy#2]
# install my visualizer
cd visualizer && pip install -e . && cd ..
pip install kaleido plotly open3d tyro termcolor h5py
cd ..

In this step, we should cd in visualizer, but this folder does not exist. Did you miss it when uploading?

**Comment by YanjieZe** [comment]
Hi it is under "third_party". Thank you for reporting the problem.
