### ISSUE TITLE
[Question] Choice of training epochs

### ISSUE THREAD

**Issue by rechim25** [YanjieZe/Improved-3D-Diffusion-Policy#6]
Hi authors, thanks for this amazing project!

I'm wondering how the choice for 300 training epochs was made? In the previous DP3 paper tasks were trained for more than 300 in some cases even for 3000 epochs. Also wondering why there is such a difference

Thank you!

**Comment by YanjieZe** [comment]
Hi, thank you for your interest. The 300 epochs are the same as [Bunny-VisionPro](https://arxiv.org/abs/2407.03162) paper. This is just mainly because 300 epochs are sufficient, so to save time we do not train more.
