### ISSUE TITLE
ModuleNotFoundError: No module named 'communication'

### ISSUE THREAD

**Issue by cvJie** [YanjieZe/Improved-3D-Diffusion-Policy#7]
win10

when to run ：bash scripts/deploy_policy.sh idp3 gr1_dex-3d 0913_example，
here will occur ModuleNotFoundError: No module named 'communication' and ModuleNotFoundError: No module named 'retarget',

and i can't found  "communication" and "retarget"  pip python  modules or python code.

can you help me?

thanks

**Comment by YanjieZe** [comment]
Hi, thank you for your interest. As I mention in README, the deployment file is tailored for the specific robot. Thus it needs some robot API. The robot API for the used humanoid robot is provided here:
https://github.com/YanjieZe/Humanoid-Teleoperation/blob/main/humanoid_teleoperation/teleop-zenoh/communication.py
