### ISSUE TITLE
About the improved visual encoder

### ISSUE THREAD

**Issue by JLHins** [YanjieZe/Improved-3D-Diffusion-Policy#8]
Hi, thanks for sharing the great work.

The results in this paper demonstrate a performance boost with a stronger visual encoder, but in the previous DP3 we get the opposite. How should we understand the difference here?

**Comment by YanjieZe** [comment]
Hi, thank you for your interest. If you mean the ablation exp in DP3, I think the visual encoder of iDP3 is different from the ones ablated in DP3. We are not showing a *strong* encoder is not good for DP3, bu showing most other encoders are not suitable.
